let _collections = [{
    url: "solanadogesnfts",
    name: "SolanaDoges",
    marketplace: [],
    img: "solanadogenft.png",
    featured: false,
    discord: "https://t.co/zeJaS54GOV?amp=1",
    twitter: "https://twitter.com/SolanaDogeNFTs",
    digitaleyes: "https://digitaleyes.market/collections/SolanaDogeNFTs",
    fp: 0,
  },
  {
    url: "thugbirdz",
    name: "Thugbirdz",
    marketplace: [],
    img: "thugbirdz.png",
    featured: true,
    discord: "https://discord.gg/gdJM2MFz",
    twitter: "https://twitter.com/thugbirdz",
    digitaleyes: "https://digitaleyes.market/collections/Thugbirdz",
    fp: 0,
  },
  {
    url: "degenapes",
    name: "Degen Ape Academy",
    marketplace: [],
    img: "degenape.jpg",
    featured: false,
    
    fp: 0,
  },
  {
    url: "abstratica",
    name: "Abstratica",
    marketplace: [],
    img: "abstratica.gif",
    featured: false,
    fp: 0,

  },
  {
    url: "solpops",
    name: "Solpops",
    marketplace: [],
    img: "solpop.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "soliens",
    name: "Soliens",
    marketplace: [],
    img: "soliens.jpeg",
    featured: false,
    fp: 0,
  },
  {
    url: "soldalas",
    name: "Soldalas",
    marketplace: [],
    img: "soldalas.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "solanimals",
    name: "Solanimals",
    marketplace: [],
    img: "solanimal.png",
    featured: false,
    fp: 0,
  },
  {
    url: "pixelpenguin",
    name: "PixelPenguins",
    marketplace: [],
    img: "pixelpenguin.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "frakt",
    name: "Frakt",
    marketplace: [],
    img: "frakt.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "solchihuahua",
    name: "SolChihuahua",
    marketplace: [],
    img: "chihuahua.jpeg",
    featured: false,
    fp: 0,
  },
  {
    url: "smb",
    name: "SMB",
    marketplace: [],
    img: "smb.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solbear",
    name: "SolBear",
    marketplace: [],
    img: "solbear.png",
    featured: false,
    fp: 0,
  },
  {
    url: "sollamas-gen2",
    name: "Sollamas",
    marketplace: [],
    img: "sollamas.png",
    featured: false,
    fp: 0,
  },
  {
    url: "boldbadgers",
    name: "Boldbadgers",
    marketplace: [],
    img: "boldbadger.webp",
    featured: false,
    fp: 0,
  },
  {
    url: "solpunks",
    name: "Solpunks",
    marketplace: [],
    img: "solpunk.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solarians",
    name: "Solarians",
    marketplace: [],
    img: "solarian.gif",
    featured: false,
    fp: 0,
  },
  {
    url: "tophatchicks",
    name: "TopHatChicks",
    marketplace: [],
    img: "tophatchicks.png",
    featured: false,
    fp: 0,
  },
  {
    url: "rox",
    name: "Rox",
    marketplace: [],
    img: "rox.jpeg",
    featured: false,
    fp: 0,
  },
  {
    url: "aurory",
    name: "Aurory",
    marketplace: [],
    img: "aurory.png",
    featured: false,
    fp: 0,
  },
  {
    url: "cryptolizzy",
    name: "CryptoLizzy",
    marketplace: [],
    img: "cryptolizzy.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solanasouls",
    name: "Solana Souls",
    marketplace: [],
    img: "solanasouls.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "solamanders",
    name: "Solamanders",
    marketplace: [],
    img: "solamanders.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solbulls",
    name: "Solbulls",
    marketplace: [],
    img: "solbulls.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solcats",
    name: "SolCats",
    marketplace: [],
    img: "solcats.png",
    featured: false,
    fp: 0,
  },
  {
    url: "bitboat",
    name: "BitBoat",
    marketplace: [],
    img: "bitboat.png",
    featured: false,
    fp: 0,
  },
  {
    url: "legionpunks",
    name: "Legion Punks",
    marketplace: [],
    img: "legionpunks.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solstash",
    name: "SolStash",
    marketplace: [],
    img: "solstash.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "kaijucards",
    name: "Kaiju Cards",
    marketplace: [],
    img: "kaijucards.png",
    featured: false,
    fp: 0,
  },
  {
    url: "piggysolgang",
    name: "Piggy Sol Gang",
    marketplace: [],
    img: "piggysolgang.jpg",
    featured: false,
    fp: 0,
  },
  {
    url: "gmoot",
    name: "Gmoot",
    marketplace: [],
    img: "gmoot.png",
    featured: false,
    fp: 0,
  },
  {
    url: "solgen",
    name: "SolGen",
    marketplace: [],
    img: "solgen.png",
    featured: false,
    fp: 0,
  },
  {
    url: "trippybunnytribe",
    name: "Trippy Bunny Tribe",
    marketplace: [],
    img: "trippybunnytribe.png",
    featured: false,
    fp: 0,
  },
  {
    url: "boogle",
    name: "Boogle",
    marketplace: [],
    img: "boogle.jpg",
    featured: false,
    fp: 0,
  },

  
];

export default _collections;