let _collections = [{
    url: "solanadogesnfts",
    name: "SolanaDoges",
    marketplace: [],
    img: "solanadogenft.png",
    featured: true,
    discord: "https://t.co/zeJaS54GOV?amp=1",
    twitter: "https://twitter.com/SolanaDogeNFTs",
    website: "https://t.co/9ZSM9CbHkY?amp=1"
  },
  {
    url: "thugbirdz",
    name: "Thugbirdz",
    marketplace: [],
    img: "thugbirdz.png",
    featured: false,
  },
  {
    url: "degenapes",
    name: "Degen Ape Academy",
    marketplace: [],
    img: "degenape.jpg",
    featured: false,
  },
  {
    url: "abstratica",
    name: "Abstratica",
    marketplace: [],
    img: "abstratica.gif",
    featured: false,

  },
  {
    url: "solpops",
    name: "Solpops",
    marketplace: [],
    img: "solpop.jpg",
    featured: false,
  },
  {
    url: "soliens",
    name: "Soliens",
    marketplace: [],
    img: "soliens.jpeg",
    featured: false,
  },
  {
    url: "soldalas",
    name: "Soldalas",
    marketplace: [],
    img: "soldalas.jpg",
    featured: false,
  },
  {
    url: "solanimals",
    name: "Solanimals",
    marketplace: [],
    img: "solanimal.png",
    featured: false,
  },
  {
    url: "pixelpenguin",
    name: "PixelPenguins",
    marketplace: [],
    img: "pixelpenguin.jpg",
    featured: false,
  },
  {
    url: "frakt",
    name: "Frakt",
    marketplace: [],
    img: "frakt.jpg",
    featured: false,
  },
  {
    url: "solchihuahua",
    name: "SolChihuahua",
    marketplace: [],
    img: "chihuahua.jpeg",
    featured: false,
  },
  {
    url: "smb",
    name: "SMB",
    marketplace: [],
    img: "smb.png",
    featured: false,
  },
  {
    url: "solbear",
    name: "SolBear",
    marketplace: [],
    img: "solbear.png",
    featured: false,
  },
  {
    url: "sollamas-gen2",
    name: "Sollamas",
    marketplace: [],
    img: "sollamas.png",
    featured: false,
  },
  {
    url: "boldbadgers",
    name: "Boldbadgers",
    marketplace: [],
    img: "boldbadger.webp",
    featured: false,
  },
  {
    url: "solpunks",
    name: "Solpunks",
    marketplace: [],
    img: "solpunk.png",
    featured: false,
  },
  {
    url: "solarians",
    name: "Solarians",
    marketplace: [],
    img: "solarian.gif",
    featured: false,
  },
  {
    url: "tophatchicks",
    name: "TopHatChicks",
    marketplace: [],
    img: "tophatchicks.png",
    featured: false,
  },
  {
    url: "rox",
    name: "Rox",
    marketplace: [],
    img: "rox.jpeg",
    featured: false,
  },
  {
    url: "aurory",
    name: "❌Aurory",
    marketplace: [],
    img: "aurory.png",
    featured: false,
  },
];

export default _collections;